-- Step 30: cities reference table, seed, profiles/events use city_id
-- Data wipe: truncates app tables (see list below). Re-seed auth/profiles via signup.
-- Default signup city UUID must match lib/db/default-city.ts

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE cities (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  state_name text NOT NULL,
  state_code char(2) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_cities_name_search ON cities USING gin (name gin_trgm_ops);
CREATE UNIQUE INDEX idx_cities_name_state ON cities (name, state_code);

ALTER TABLE cities ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Cities are readable by authenticated users"
  ON cities FOR SELECT
  TO authenticated
  USING (true);

-- Reserved default for new signups until user picks a home city (Step 31+ UI)
INSERT INTO cities (id, name, state_name, state_code) VALUES
  ('11111111-1111-4111-8111-111111111111', 'Los Angeles', 'California', 'CA');
-- ~1000 cities from Plotly public sample (population filter >= 25,000)
INSERT INTO cities (name, state_name, state_code) VALUES
  ('Anchorage', 'Alaska', 'AK'),
  ('Auburn', 'Alabama', 'AL'),
  ('Birmingham', 'Alabama', 'AL'),
  ('Decatur', 'Alabama', 'AL'),
  ('Dothan', 'Alabama', 'AL'),
  ('Florence', 'Alabama', 'AL'),
  ('Hoover', 'Alabama', 'AL'),
  ('Huntsville', 'Alabama', 'AL'),
  ('Madison', 'Alabama', 'AL'),
  ('Mobile', 'Alabama', 'AL'),
  ('Montgomery', 'Alabama', 'AL'),
  ('Phenix City', 'Alabama', 'AL'),
  ('Tuscaloosa', 'Alabama', 'AL'),
  ('Bentonville', 'Arkansas', 'AR'),
  ('Conway', 'Arkansas', 'AR'),
  ('Fayetteville', 'Arkansas', 'AR'),
  ('Fort Smith', 'Arkansas', 'AR'),
  ('Jonesboro', 'Arkansas', 'AR'),
  ('Little Rock', 'Arkansas', 'AR'),
  ('North Little Rock', 'Arkansas', 'AR'),
  ('Pine Bluff', 'Arkansas', 'AR'),
  ('Rogers', 'Arkansas', 'AR'),
  ('Springdale', 'Arkansas', 'AR'),
  ('Apache Junction', 'Arizona', 'AZ'),
  ('Avondale', 'Arizona', 'AZ'),
  ('Buckeye', 'Arizona', 'AZ'),
  ('Bullhead City', 'Arizona', 'AZ'),
  ('Casa Grande', 'Arizona', 'AZ'),
  ('Chandler', 'Arizona', 'AZ'),
  ('Flagstaff', 'Arizona', 'AZ'),
  ('Gilbert', 'Arizona', 'AZ'),
  ('Glendale', 'Arizona', 'AZ'),
  ('Goodyear', 'Arizona', 'AZ'),
  ('Lake Havasu City', 'Arizona', 'AZ'),
  ('Marana', 'Arizona', 'AZ'),
  ('Maricopa', 'Arizona', 'AZ'),
  ('Mesa', 'Arizona', 'AZ'),
  ('Oro Valley', 'Arizona', 'AZ'),
  ('Peoria', 'Arizona', 'AZ'),
  ('Phoenix', 'Arizona', 'AZ'),
  ('Prescott', 'Arizona', 'AZ'),
  ('Prescott Valley', 'Arizona', 'AZ'),
  ('Scottsdale', 'Arizona', 'AZ'),
  ('Sierra Vista', 'Arizona', 'AZ'),
  ('Surprise', 'Arizona', 'AZ'),
  ('Tempe', 'Arizona', 'AZ'),
  ('Tucson', 'Arizona', 'AZ'),
  ('Yuma', 'Arizona', 'AZ'),
  ('Alameda', 'California', 'CA'),
  ('Alhambra', 'California', 'CA'),
  ('Aliso Viejo', 'California', 'CA'),
  ('Anaheim', 'California', 'CA'),
  ('Antioch', 'California', 'CA'),
  ('Apple Valley', 'California', 'CA'),
  ('Arcadia', 'California', 'CA'),
  ('Azusa', 'California', 'CA'),
  ('Bakersfield', 'California', 'CA'),
  ('Baldwin Park', 'California', 'CA'),
  ('Beaumont', 'California', 'CA'),
  ('Bell Gardens', 'California', 'CA'),
  ('Bellflower', 'California', 'CA'),
  ('Berkeley', 'California', 'CA'),
  ('Brea', 'California', 'CA'),
  ('Brentwood', 'California', 'CA'),
  ('Buena Park', 'California', 'CA'),
  ('Burbank', 'California', 'CA'),
  ('Calexico', 'California', 'CA'),
  ('Camarillo', 'California', 'CA'),
  ('Campbell', 'California', 'CA'),
  ('Carlsbad', 'California', 'CA'),
  ('Carson', 'California', 'CA'),
  ('Cathedral City', 'California', 'CA'),
  ('Ceres', 'California', 'CA'),
  ('Cerritos', 'California', 'CA'),
  ('Chico', 'California', 'CA'),
  ('Chino', 'California', 'CA'),
  ('Chino Hills', 'California', 'CA'),
  ('Chula Vista', 'California', 'CA'),
  ('Citrus Heights', 'California', 'CA'),
  ('Clovis', 'California', 'CA'),
  ('Coachella', 'California', 'CA'),
  ('Colton', 'California', 'CA'),
  ('Compton', 'California', 'CA'),
  ('Concord', 'California', 'CA'),
  ('Corona', 'California', 'CA'),
  ('Costa Mesa', 'California', 'CA'),
  ('Covina', 'California', 'CA'),
  ('Culver City', 'California', 'CA'),
  ('Cupertino', 'California', 'CA'),
  ('Cypress', 'California', 'CA'),
  ('Daly City', 'California', 'CA'),
  ('Danville', 'California', 'CA'),
  ('Davis', 'California', 'CA'),
  ('Delano', 'California', 'CA'),
  ('Diamond Bar', 'California', 'CA'),
  ('Downey', 'California', 'CA'),
  ('Dublin', 'California', 'CA'),
  ('Eastvale', 'California', 'CA'),
  ('El Cajon', 'California', 'CA'),
  ('El Centro', 'California', 'CA'),
  ('El Monte', 'California', 'CA'),
  ('Elk Grove', 'California', 'CA'),
  ('Encinitas', 'California', 'CA'),
  ('Escondido', 'California', 'CA'),
  ('Fairfield', 'California', 'CA'),
  ('Folsom', 'California', 'CA'),
  ('Fontana', 'California', 'CA'),
  ('Fountain Valley', 'California', 'CA'),
  ('Fremont', 'California', 'CA'),
  ('Fresno', 'California', 'CA'),
  ('Fullerton', 'California', 'CA'),
  ('Garden Grove', 'California', 'CA'),
  ('Gardena', 'California', 'CA'),
  ('Gilroy', 'California', 'CA'),
  ('Glendale', 'California', 'CA'),
  ('Glendora', 'California', 'CA'),
  ('Hanford', 'California', 'CA'),
  ('Hawthorne', 'California', 'CA'),
  ('Hayward', 'California', 'CA'),
  ('Hemet', 'California', 'CA'),
  ('Hesperia', 'California', 'CA'),
  ('Highland', 'California', 'CA'),
  ('Huntington Beach', 'California', 'CA'),
  ('Huntington Park', 'California', 'CA'),
  ('Indio', 'California', 'CA'),
  ('Inglewood', 'California', 'CA'),
  ('Irvine', 'California', 'CA'),
  ('Jurupa Valley', 'California', 'CA'),
  ('La Habra', 'California', 'CA'),
  ('La Mesa', 'California', 'CA'),
  ('La Mirada', 'California', 'CA'),
  ('La Puente', 'California', 'CA'),
  ('La Quinta', 'California', 'CA'),
  ('Laguna Niguel', 'California', 'CA'),
  ('Lake Elsinore', 'California', 'CA'),
  ('Lake Forest', 'California', 'CA'),
  ('Lakewood', 'California', 'CA'),
  ('Lancaster', 'California', 'CA'),
  ('Lincoln', 'California', 'CA'),
  ('Livermore', 'California', 'CA'),
  ('Lodi', 'California', 'CA'),
  ('Lompoc', 'California', 'CA'),
  ('Long Beach', 'California', 'CA'),
  ('Los Angeles', 'California', 'CA'),
  ('Lynwood', 'California', 'CA'),
  ('Madera', 'California', 'CA'),
  ('Manteca', 'California', 'CA'),
  ('Martinez', 'California', 'CA'),
  ('Menifee', 'California', 'CA'),
  ('Merced', 'California', 'CA'),
  ('Milpitas', 'California', 'CA'),
  ('Mission Viejo', 'California', 'CA'),
  ('Modesto', 'California', 'CA'),
  ('Monrovia', 'California', 'CA'),
  ('Montclair', 'California', 'CA'),
  ('Montebello', 'California', 'CA'),
  ('Monterey Park', 'California', 'CA'),
  ('Moreno Valley', 'California', 'CA'),
  ('Morgan Hill', 'California', 'CA'),
  ('Mountain View', 'California', 'CA'),
  ('Murrieta', 'California', 'CA'),
  ('Napa', 'California', 'CA'),
  ('National City', 'California', 'CA'),
  ('Newark', 'California', 'CA'),
  ('Newport Beach', 'California', 'CA'),
  ('Norwalk', 'California', 'CA'),
  ('Novato', 'California', 'CA'),
  ('Oakland', 'California', 'CA'),
  ('Oakley', 'California', 'CA'),
  ('Oceanside', 'California', 'CA'),
  ('Ontario', 'California', 'CA'),
  ('Orange', 'California', 'CA'),
  ('Oxnard', 'California', 'CA'),
  ('Pacifica', 'California', 'CA'),
  ('Palm Desert', 'California', 'CA'),
  ('Palm Springs', 'California', 'CA'),
  ('Palmdale', 'California', 'CA'),
  ('Palo Alto', 'California', 'CA'),
  ('Paramount', 'California', 'CA'),
  ('Pasadena', 'California', 'CA'),
  ('Perris', 'California', 'CA'),
  ('Petaluma', 'California', 'CA'),
  ('Pico Rivera', 'California', 'CA'),
  ('Pittsburg', 'California', 'CA'),
  ('Placentia', 'California', 'CA'),
  ('Pleasanton', 'California', 'CA'),
  ('Pomona', 'California', 'CA'),
  ('Porterville', 'California', 'CA'),
  ('Poway', 'California', 'CA'),
  ('Rancho Cordova', 'California', 'CA'),
  ('Rancho Cucamonga', 'California', 'CA'),
  ('Rancho Palos Verdes', 'California', 'CA'),
  ('Rancho Santa Margarita', 'California', 'CA'),
  ('Redding', 'California', 'CA'),
  ('Redlands', 'California', 'CA'),
  ('Redondo Beach', 'California', 'CA'),
  ('Redwood City', 'California', 'CA'),
  ('Rialto', 'California', 'CA'),
  ('Richmond', 'California', 'CA'),
  ('Riverside', 'California', 'CA'),
  ('Rocklin', 'California', 'CA'),
  ('Rohnert Park', 'California', 'CA'),
  ('Rosemead', 'California', 'CA'),
  ('Roseville', 'California', 'CA'),
  ('Sacramento', 'California', 'CA'),
  ('Salinas', 'California', 'CA'),
  ('San Bernardino', 'California', 'CA'),
  ('San Bruno', 'California', 'CA'),
  ('San Buenaventura (Ventura)', 'California', 'CA'),
  ('San Clemente', 'California', 'CA'),
  ('San Diego', 'California', 'CA'),
  ('San Francisco', 'California', 'CA'),
  ('San Gabriel', 'California', 'CA'),
  ('San Jacinto', 'California', 'CA'),
  ('San Jose', 'California', 'CA'),
  ('San Leandro', 'California', 'CA'),
  ('San Luis Obispo', 'California', 'CA'),
  ('San Marcos', 'California', 'CA'),
  ('San Mateo', 'California', 'CA'),
  ('San Rafael', 'California', 'CA'),
  ('San Ramon', 'California', 'CA'),
  ('Santa Ana', 'California', 'CA'),
  ('Santa Barbara', 'California', 'CA'),
  ('Santa Clara', 'California', 'CA'),
  ('Santa Clarita', 'California', 'CA'),
  ('Santa Cruz', 'California', 'CA'),
  ('Santa Maria', 'California', 'CA'),
  ('Santa Monica', 'California', 'CA'),
  ('Santa Rosa', 'California', 'CA'),
  ('Santee', 'California', 'CA'),
  ('Simi Valley', 'California', 'CA'),
  ('South Gate', 'California', 'CA'),
  ('South San Francisco', 'California', 'CA'),
  ('Stanton', 'California', 'CA'),
  ('Stockton', 'California', 'CA'),
  ('Sunnyvale', 'California', 'CA'),
  ('Temecula', 'California', 'CA'),
  ('Thousand Oaks', 'California', 'CA'),
  ('Torrance', 'California', 'CA'),
  ('Tracy', 'California', 'CA'),
  ('Tulare', 'California', 'CA'),
  ('Turlock', 'California', 'CA'),
  ('Tustin', 'California', 'CA'),
  ('Union City', 'California', 'CA'),
  ('Upland', 'California', 'CA'),
  ('Vacaville', 'California', 'CA'),
  ('Vallejo', 'California', 'CA'),
  ('Victorville', 'California', 'CA'),
  ('Visalia', 'California', 'CA'),
  ('Vista', 'California', 'CA'),
  ('Walnut Creek', 'California', 'CA'),
  ('Watsonville', 'California', 'CA'),
  ('West Covina', 'California', 'CA'),
  ('West Sacramento', 'California', 'CA'),
  ('Westminster', 'California', 'CA'),
  ('Whittier', 'California', 'CA'),
  ('Woodland', 'California', 'CA'),
  ('Yorba Linda', 'California', 'CA'),
  ('Yuba City', 'California', 'CA'),
  ('Yucaipa', 'California', 'CA'),
  ('Arvada', 'Colorado', 'CO'),
  ('Aurora', 'Colorado', 'CO'),
  ('Boulder', 'Colorado', 'CO'),
  ('Broomfield', 'Colorado', 'CO'),
  ('Castle Rock', 'Colorado', 'CO'),
  ('Centennial', 'Colorado', 'CO'),
  ('Colorado Springs', 'Colorado', 'CO'),
  ('Commerce City', 'Colorado', 'CO'),
  ('Denver', 'Colorado', 'CO'),
  ('Fort Collins', 'Colorado', 'CO'),
  ('Grand Junction', 'Colorado', 'CO'),
  ('Greeley', 'Colorado', 'CO'),
  ('Lakewood', 'Colorado', 'CO'),
  ('Littleton', 'Colorado', 'CO'),
  ('Longmont', 'Colorado', 'CO'),
  ('Loveland', 'Colorado', 'CO'),
  ('Northglenn', 'Colorado', 'CO'),
  ('Parker', 'Colorado', 'CO'),
  ('Pueblo', 'Colorado', 'CO'),
  ('Thornton', 'Colorado', 'CO'),
  ('Westminster', 'Colorado', 'CO'),
  ('Bridgeport', 'Connecticut', 'CT'),
  ('Bristol', 'Connecticut', 'CT'),
  ('Danbury', 'Connecticut', 'CT'),
  ('Hartford', 'Connecticut', 'CT'),
  ('Meriden', 'Connecticut', 'CT'),
  ('Middletown', 'Connecticut', 'CT'),
  ('Milford', 'Connecticut', 'CT'),
  ('New Britain', 'Connecticut', 'CT'),
  ('New Haven', 'Connecticut', 'CT'),
  ('Norwalk', 'Connecticut', 'CT'),
  ('Norwich', 'Connecticut', 'CT'),
  ('Shelton', 'Connecticut', 'CT'),
  ('Stamford', 'Connecticut', 'CT'),
  ('Waterbury', 'Connecticut', 'CT'),
  ('West Haven', 'Connecticut', 'CT'),
  ('Washington', 'District of Columbia', 'DC'),
  ('Dover', 'Delaware', 'DE'),
  ('Wilmington', 'Delaware', 'DE'),
  ('Altamonte Springs', 'Florida', 'FL'),
  ('Apopka', 'Florida', 'FL'),
  ('Aventura', 'Florida', 'FL'),
  ('Boca Raton', 'Florida', 'FL'),
  ('Bonita Springs', 'Florida', 'FL'),
  ('Boynton Beach', 'Florida', 'FL'),
  ('Bradenton', 'Florida', 'FL'),
  ('Cape Coral', 'Florida', 'FL'),
  ('Clearwater', 'Florida', 'FL'),
  ('Coconut Creek', 'Florida', 'FL'),
  ('Coral Gables', 'Florida', 'FL'),
  ('Coral Springs', 'Florida', 'FL'),
  ('Cutler Bay', 'Florida', 'FL'),
  ('Davie', 'Florida', 'FL'),
  ('Daytona Beach', 'Florida', 'FL'),
  ('Deerfield Beach', 'Florida', 'FL'),
  ('Delray Beach', 'Florida', 'FL'),
  ('Deltona', 'Florida', 'FL'),
  ('Doral', 'Florida', 'FL'),
  ('Fort Lauderdale', 'Florida', 'FL'),
  ('Fort Myers', 'Florida', 'FL'),
  ('Fort Pierce', 'Florida', 'FL'),
  ('Gainesville', 'Florida', 'FL'),
  ('Greenacres', 'Florida', 'FL'),
  ('Hallandale Beach', 'Florida', 'FL'),
  ('Hialeah', 'Florida', 'FL'),
  ('Hollywood', 'Florida', 'FL'),
  ('Homestead', 'Florida', 'FL'),
  ('Jacksonville', 'Florida', 'FL'),
  ('Jupiter', 'Florida', 'FL'),
  ('Kissimmee', 'Florida', 'FL'),
  ('Lakeland', 'Florida', 'FL'),
  ('Largo', 'Florida', 'FL'),
  ('Lauderhill', 'Florida', 'FL'),
  ('Margate', 'Florida', 'FL'),
  ('Melbourne', 'Florida', 'FL'),
  ('Miami', 'Florida', 'FL'),
  ('Miami Beach', 'Florida', 'FL'),
  ('Miami Gardens', 'Florida', 'FL'),
  ('Miramar', 'Florida', 'FL'),
  ('North Lauderdale', 'Florida', 'FL'),
  ('North Miami', 'Florida', 'FL'),
  ('North Miami Beach', 'Florida', 'FL'),
  ('North Port', 'Florida', 'FL'),
  ('Oakland Park', 'Florida', 'FL'),
  ('Ocala', 'Florida', 'FL'),
  ('Ocoee', 'Florida', 'FL'),
  ('Orlando', 'Florida', 'FL'),
  ('Ormond Beach', 'Florida', 'FL'),
  ('Palm Bay', 'Florida', 'FL'),
  ('Palm Beach Gardens', 'Florida', 'FL'),
  ('Palm Coast', 'Florida', 'FL'),
  ('Panama City', 'Florida', 'FL'),
  ('Pembroke Pines', 'Florida', 'FL'),
  ('Pensacola', 'Florida', 'FL'),
  ('Pinellas Park', 'Florida', 'FL'),
  ('Plantation', 'Florida', 'FL'),
  ('Pompano Beach', 'Florida', 'FL'),
  ('Port Orange', 'Florida', 'FL'),
  ('Port St. Lucie', 'Florida', 'FL'),
  ('Sanford', 'Florida', 'FL'),
  ('Sarasota', 'Florida', 'FL'),
  ('St. Cloud', 'Florida', 'FL'),
  ('St. Petersburg', 'Florida', 'FL'),
  ('Sunrise', 'Florida', 'FL'),
  ('Tallahassee', 'Florida', 'FL'),
  ('Tamarac', 'Florida', 'FL'),
  ('Tampa', 'Florida', 'FL'),
  ('Titusville', 'Florida', 'FL'),
  ('Wellington', 'Florida', 'FL'),
  ('West Palm Beach', 'Florida', 'FL'),
  ('Weston', 'Florida', 'FL'),
  ('Winter Garden', 'Florida', 'FL'),
  ('Albany', 'Georgia', 'GA'),
  ('Alpharetta', 'Georgia', 'GA'),
  ('Athens-Clarke County', 'Georgia', 'GA'),
  ('Atlanta', 'Georgia', 'GA'),
  ('Augusta-Richmond County', 'Georgia', 'GA'),
  ('Brookhaven', 'Georgia', 'GA'),
  ('Columbus', 'Georgia', 'GA'),
  ('Dunwoody', 'Georgia', 'GA'),
  ('Johns Creek', 'Georgia', 'GA'),
  ('Macon', 'Georgia', 'GA'),
  ('Marietta', 'Georgia', 'GA'),
  ('Peachtree Corners', 'Georgia', 'GA'),
  ('Roswell', 'Georgia', 'GA'),
  ('Sandy Springs', 'Georgia', 'GA'),
  ('Savannah', 'Georgia', 'GA'),
  ('Smyrna', 'Georgia', 'GA'),
  ('Valdosta', 'Georgia', 'GA'),
  ('Warner Robins', 'Georgia', 'GA'),
  ('Honolulu', 'Hawaii', 'HI'),
  ('Ames', 'Iowa', 'IA'),
  ('Ankeny', 'Iowa', 'IA'),
  ('Cedar Falls', 'Iowa', 'IA'),
  ('Cedar Rapids', 'Iowa', 'IA'),
  ('Council Bluffs', 'Iowa', 'IA'),
  ('Davenport', 'Iowa', 'IA'),
  ('Des Moines', 'Iowa', 'IA'),
  ('Dubuque', 'Iowa', 'IA'),
  ('Iowa City', 'Iowa', 'IA'),
  ('Sioux City', 'Iowa', 'IA'),
  ('Urbandale', 'Iowa', 'IA'),
  ('Waterloo', 'Iowa', 'IA'),
  ('West Des Moines', 'Iowa', 'IA'),
  ('Boise City', 'Idaho', 'ID'),
  ('Caldwell', 'Idaho', 'ID'),
  ('Coeur d''Alene', 'Idaho', 'ID'),
  ('Idaho Falls', 'Idaho', 'ID'),
  ('Meridian', 'Idaho', 'ID'),
  ('Nampa', 'Idaho', 'ID'),
  ('Pocatello', 'Idaho', 'ID'),
  ('Twin Falls', 'Idaho', 'ID'),
  ('Addison', 'Illinois', 'IL'),
  ('Arlington Heights', 'Illinois', 'IL'),
  ('Aurora', 'Illinois', 'IL'),
  ('Bartlett', 'Illinois', 'IL'),
  ('Belleville', 'Illinois', 'IL'),
  ('Berwyn', 'Illinois', 'IL'),
  ('Bloomington', 'Illinois', 'IL'),
  ('Bolingbrook', 'Illinois', 'IL'),
  ('Buffalo Grove', 'Illinois', 'IL'),
  ('Calumet City', 'Illinois', 'IL'),
  ('Carol Stream', 'Illinois', 'IL'),
  ('Carpentersville', 'Illinois', 'IL'),
  ('Champaign', 'Illinois', 'IL'),
  ('Chicago', 'Illinois', 'IL'),
  ('Cicero', 'Illinois', 'IL'),
  ('Crystal Lake', 'Illinois', 'IL'),
  ('Decatur', 'Illinois', 'IL'),
  ('DeKalb', 'Illinois', 'IL'),
  ('Des Plaines', 'Illinois', 'IL'),
  ('Downers Grove', 'Illinois', 'IL'),
  ('Elgin', 'Illinois', 'IL'),
  ('Elmhurst', 'Illinois', 'IL'),
  ('Evanston', 'Illinois', 'IL'),
  ('Glenview', 'Illinois', 'IL'),
  ('Hanover Park', 'Illinois', 'IL'),
  ('Hoffman Estates', 'Illinois', 'IL'),
  ('Joliet', 'Illinois', 'IL'),
  ('Lombard', 'Illinois', 'IL'),
  ('Moline', 'Illinois', 'IL'),
  ('Mount Prospect', 'Illinois', 'IL'),
  ('Naperville', 'Illinois', 'IL'),
  ('Normal', 'Illinois', 'IL'),
  ('Oak Lawn', 'Illinois', 'IL'),
  ('Oak Park', 'Illinois', 'IL'),
  ('Orland Park', 'Illinois', 'IL'),
  ('Palatine', 'Illinois', 'IL'),
  ('Park Ridge', 'Illinois', 'IL'),
  ('Peoria', 'Illinois', 'IL'),
  ('Plainfield', 'Illinois', 'IL'),
  ('Quincy', 'Illinois', 'IL'),
  ('Rock Island', 'Illinois', 'IL'),
  ('Rockford', 'Illinois', 'IL'),
  ('Romeoville', 'Illinois', 'IL'),
  ('Schaumburg', 'Illinois', 'IL'),
  ('Skokie', 'Illinois', 'IL'),
  ('Springfield', 'Illinois', 'IL'),
  ('Streamwood', 'Illinois', 'IL'),
  ('Tinley Park', 'Illinois', 'IL'),
  ('Urbana', 'Illinois', 'IL'),
  ('Waukegan', 'Illinois', 'IL'),
  ('Wheaton', 'Illinois', 'IL'),
  ('Wheeling', 'Illinois', 'IL'),
  ('Anderson', 'Indiana', 'IN'),
  ('Bloomington', 'Indiana', 'IN'),
  ('Carmel', 'Indiana', 'IN'),
  ('Columbus', 'Indiana', 'IN'),
  ('Elkhart', 'Indiana', 'IN'),
  ('Evansville', 'Indiana', 'IN'),
  ('Fishers', 'Indiana', 'IN'),
  ('Fort Wayne', 'Indiana', 'IN'),
  ('Gary', 'Indiana', 'IN'),
  ('Greenwood', 'Indiana', 'IN'),
  ('Hammond', 'Indiana', 'IN'),
  ('Indianapolis', 'Indiana', 'IN'),
  ('Jeffersonville', 'Indiana', 'IN'),
  ('Kokomo', 'Indiana', 'IN'),
  ('Lafayette', 'Indiana', 'IN'),
  ('Lawrence', 'Indiana', 'IN'),
  ('Mishawaka', 'Indiana', 'IN'),
  ('Muncie', 'Indiana', 'IN'),
  ('Noblesville', 'Indiana', 'IN'),
  ('South Bend', 'Indiana', 'IN'),
  ('Terre Haute', 'Indiana', 'IN'),
  ('Hutchinson', 'Kansas', 'KS'),
  ('Kansas City', 'Kansas', 'KS'),
  ('Lawrence', 'Kansas', 'KS'),
  ('Lenexa', 'Kansas', 'KS'),
  ('Manhattan', 'Kansas', 'KS'),
  ('Olathe', 'Kansas', 'KS'),
  ('Overland Park', 'Kansas', 'KS'),
  ('Salina', 'Kansas', 'KS'),
  ('Shawnee', 'Kansas', 'KS'),
  ('Topeka', 'Kansas', 'KS'),
  ('Wichita', 'Kansas', 'KS'),
  ('Bowling Green', 'Kentucky', 'KY'),
  ('Covington', 'Kentucky', 'KY'),
  ('Lexington-Fayette', 'Kentucky', 'KY'),
  ('Louisville', 'Kentucky', 'KY'),
  ('Owensboro', 'Kentucky', 'KY'),
  ('Alexandria', 'Louisiana', 'LA'),
  ('Baton Rouge', 'Louisiana', 'LA'),
  ('Bossier City', 'Louisiana', 'LA'),
  ('Kenner', 'Louisiana', 'LA'),
  ('Lafayette', 'Louisiana', 'LA'),
  ('Lake Charles', 'Louisiana', 'LA'),
  ('Monroe', 'Louisiana', 'LA'),
  ('New Orleans', 'Louisiana', 'LA'),
  ('Shreveport', 'Louisiana', 'LA'),
  ('Attleboro', 'Massachusetts', 'MA'),
  ('Barnstable Town', 'Massachusetts', 'MA'),
  ('Beverly', 'Massachusetts', 'MA'),
  ('Boston', 'Massachusetts', 'MA'),
  ('Brockton', 'Massachusetts', 'MA'),
  ('Cambridge', 'Massachusetts', 'MA'),
  ('Chelsea', 'Massachusetts', 'MA'),
  ('Chicopee', 'Massachusetts', 'MA'),
  ('Everett', 'Massachusetts', 'MA'),
  ('Fall River', 'Massachusetts', 'MA'),
  ('Fitchburg', 'Massachusetts', 'MA'),
  ('Haverhill', 'Massachusetts', 'MA'),
  ('Holyoke', 'Massachusetts', 'MA'),
  ('Lawrence', 'Massachusetts', 'MA'),
  ('Leominster', 'Massachusetts', 'MA'),
  ('Lowell', 'Massachusetts', 'MA'),
  ('Lynn', 'Massachusetts', 'MA'),
  ('Malden', 'Massachusetts', 'MA'),
  ('Marlborough', 'Massachusetts', 'MA'),
  ('Medford', 'Massachusetts', 'MA'),
  ('Methuen', 'Massachusetts', 'MA'),
  ('New Bedford', 'Massachusetts', 'MA'),
  ('Newton', 'Massachusetts', 'MA'),
  ('Peabody', 'Massachusetts', 'MA'),
  ('Pittsfield', 'Massachusetts', 'MA'),
  ('Quincy', 'Massachusetts', 'MA'),
  ('Revere', 'Massachusetts', 'MA'),
  ('Salem', 'Massachusetts', 'MA'),
  ('Somerville', 'Massachusetts', 'MA'),
  ('Springfield', 'Massachusetts', 'MA'),
  ('Taunton', 'Massachusetts', 'MA'),
  ('Waltham', 'Massachusetts', 'MA'),
  ('Westfield', 'Massachusetts', 'MA'),
  ('Weymouth Town', 'Massachusetts', 'MA'),
  ('Woburn', 'Massachusetts', 'MA'),
  ('Worcester', 'Massachusetts', 'MA'),
  ('Annapolis', 'Maryland', 'MD'),
  ('Baltimore', 'Maryland', 'MD'),
  ('Bowie', 'Maryland', 'MD'),
  ('Frederick', 'Maryland', 'MD'),
  ('Gaithersburg', 'Maryland', 'MD'),
  ('Hagerstown', 'Maryland', 'MD'),
  ('Rockville', 'Maryland', 'MD'),
  ('Portland', 'Maine', 'ME'),
  ('Ann Arbor', 'Michigan', 'MI'),
  ('Battle Creek', 'Michigan', 'MI'),
  ('Dearborn', 'Michigan', 'MI'),
  ('Dearborn Heights', 'Michigan', 'MI'),
  ('Detroit', 'Michigan', 'MI'),
  ('East Lansing', 'Michigan', 'MI'),
  ('Farmington Hills', 'Michigan', 'MI'),
  ('Flint', 'Michigan', 'MI'),
  ('Grand Rapids', 'Michigan', 'MI'),
  ('Kalamazoo', 'Michigan', 'MI'),
  ('Kentwood', 'Michigan', 'MI'),
  ('Lansing', 'Michigan', 'MI'),
  ('Lincoln Park', 'Michigan', 'MI'),
  ('Livonia', 'Michigan', 'MI'),
  ('Midland', 'Michigan', 'MI'),
  ('Muskegon', 'Michigan', 'MI'),
  ('Novi', 'Michigan', 'MI'),
  ('Pontiac', 'Michigan', 'MI'),
  ('Portage', 'Michigan', 'MI'),
  ('Rochester Hills', 'Michigan', 'MI'),
  ('Roseville', 'Michigan', 'MI'),
  ('Royal Oak', 'Michigan', 'MI'),
  ('Saginaw', 'Michigan', 'MI'),
  ('Southfield', 'Michigan', 'MI'),
  ('St. Clair Shores', 'Michigan', 'MI'),
  ('Sterling Heights', 'Michigan', 'MI'),
  ('Taylor', 'Michigan', 'MI'),
  ('Troy', 'Michigan', 'MI'),
  ('Warren', 'Michigan', 'MI'),
  ('Westland', 'Michigan', 'MI'),
  ('Wyoming', 'Michigan', 'MI'),
  ('Apple Valley', 'Minnesota', 'MN'),
  ('Blaine', 'Minnesota', 'MN'),
  ('Bloomington', 'Minnesota', 'MN'),
  ('Brooklyn Park', 'Minnesota', 'MN'),
  ('Burnsville', 'Minnesota', 'MN'),
  ('Coon Rapids', 'Minnesota', 'MN'),
  ('Duluth', 'Minnesota', 'MN'),
  ('Eagan', 'Minnesota', 'MN'),
  ('Eden Prairie', 'Minnesota', 'MN'),
  ('Edina', 'Minnesota', 'MN'),
  ('Lakeville', 'Minnesota', 'MN'),
  ('Mankato', 'Minnesota', 'MN'),
  ('Maple Grove', 'Minnesota', 'MN'),
  ('Maplewood', 'Minnesota', 'MN'),
  ('Minneapolis', 'Minnesota', 'MN'),
  ('Minnetonka', 'Minnesota', 'MN'),
  ('Moorhead', 'Minnesota', 'MN'),
  ('Plymouth', 'Minnesota', 'MN'),
  ('Rochester', 'Minnesota', 'MN'),
  ('Shakopee', 'Minnesota', 'MN'),
  ('St. Cloud', 'Minnesota', 'MN'),
  ('St. Louis Park', 'Minnesota', 'MN'),
  ('St. Paul', 'Minnesota', 'MN'),
  ('Woodbury', 'Minnesota', 'MN'),
  ('Blue Springs', 'Missouri', 'MO'),
  ('Cape Girardeau', 'Missouri', 'MO'),
  ('Chesterfield', 'Missouri', 'MO'),
  ('Columbia', 'Missouri', 'MO'),
  ('Florissant', 'Missouri', 'MO'),
  ('Independence', 'Missouri', 'MO'),
  ('Jefferson City', 'Missouri', 'MO'),
  ('Joplin', 'Missouri', 'MO'),
  ('Kansas City', 'Missouri', 'MO'),
  ('Lee''s Summit', 'Missouri', 'MO'),
  ('O''Fallon', 'Missouri', 'MO'),
  ('Springfield', 'Missouri', 'MO'),
  ('St. Charles', 'Missouri', 'MO'),
  ('St. Joseph', 'Missouri', 'MO'),
  ('St. Louis', 'Missouri', 'MO'),
  ('St. Peters', 'Missouri', 'MO'),
  ('Biloxi', 'Mississippi', 'MS'),
  ('Gulfport', 'Mississippi', 'MS'),
  ('Hattiesburg', 'Mississippi', 'MS'),
  ('Jackson', 'Mississippi', 'MS'),
  ('Meridian', 'Mississippi', 'MS'),
  ('Southaven', 'Mississippi', 'MS'),
  ('Billings', 'Montana', 'MT'),
  ('Bozeman', 'Montana', 'MT'),
  ('Great Falls', 'Montana', 'MT'),
  ('Missoula', 'Montana', 'MT'),
  ('Apex', 'North Carolina', 'NC'),
  ('Asheville', 'North Carolina', 'NC'),
  ('Burlington', 'North Carolina', 'NC'),
  ('Cary', 'North Carolina', 'NC'),
  ('Chapel Hill', 'North Carolina', 'NC'),
  ('Charlotte', 'North Carolina', 'NC'),
  ('Concord', 'North Carolina', 'NC'),
  ('Durham', 'North Carolina', 'NC'),
  ('Fayetteville', 'North Carolina', 'NC'),
  ('Gastonia', 'North Carolina', 'NC'),
  ('Greensboro', 'North Carolina', 'NC'),
  ('Greenville', 'North Carolina', 'NC'),
  ('Hickory', 'North Carolina', 'NC'),
  ('High Point', 'North Carolina', 'NC'),
  ('Huntersville', 'North Carolina', 'NC'),
  ('Jacksonville', 'North Carolina', 'NC'),
  ('Kannapolis', 'North Carolina', 'NC'),
  ('Raleigh', 'North Carolina', 'NC'),
  ('Rocky Mount', 'North Carolina', 'NC'),
  ('Wilmington', 'North Carolina', 'NC'),
  ('Wilson', 'North Carolina', 'NC'),
  ('Winston-Salem', 'North Carolina', 'NC'),
  ('Bismarck', 'North Dakota', 'ND'),
  ('Fargo', 'North Dakota', 'ND'),
  ('Grand Forks', 'North Dakota', 'ND'),
  ('Minot', 'North Dakota', 'ND'),
  ('Bellevue', 'Nebraska', 'NE'),
  ('Grand Island', 'Nebraska', 'NE'),
  ('Lincoln', 'Nebraska', 'NE'),
  ('Omaha', 'Nebraska', 'NE'),
  ('Concord', 'New Hampshire', 'NH'),
  ('Manchester', 'New Hampshire', 'NH'),
  ('Nashua', 'New Hampshire', 'NH'),
  ('Atlantic City', 'New Jersey', 'NJ'),
  ('Bayonne', 'New Jersey', 'NJ'),
  ('Camden', 'New Jersey', 'NJ'),
  ('Clifton', 'New Jersey', 'NJ'),
  ('East Orange', 'New Jersey', 'NJ'),
  ('Elizabeth', 'New Jersey', 'NJ'),
  ('Hackensack', 'New Jersey', 'NJ'),
  ('Hoboken', 'New Jersey', 'NJ'),
  ('Jersey City', 'New Jersey', 'NJ'),
  ('Kearny', 'New Jersey', 'NJ'),
  ('Linden', 'New Jersey', 'NJ'),
  ('New Brunswick', 'New Jersey', 'NJ'),
  ('Newark', 'New Jersey', 'NJ'),
  ('Passaic', 'New Jersey', 'NJ'),
  ('Paterson', 'New Jersey', 'NJ'),
  ('Perth Amboy', 'New Jersey', 'NJ'),
  ('Plainfield', 'New Jersey', 'NJ'),
  ('Sayreville', 'New Jersey', 'NJ'),
  ('Trenton', 'New Jersey', 'NJ'),
  ('Union City', 'New Jersey', 'NJ'),
  ('Vineland', 'New Jersey', 'NJ'),
  ('West New York', 'New Jersey', 'NJ'),
  ('Albuquerque', 'New Mexico', 'NM'),
  ('Clovis', 'New Mexico', 'NM'),
  ('Farmington', 'New Mexico', 'NM'),
  ('Las Cruces', 'New Mexico', 'NM'),
  ('Rio Rancho', 'New Mexico', 'NM'),
  ('Roswell', 'New Mexico', 'NM'),
  ('Santa Fe', 'New Mexico', 'NM'),
  ('Carson City', 'Nevada', 'NV'),
  ('Henderson', 'Nevada', 'NV'),
  ('Las Vegas', 'Nevada', 'NV'),
  ('North Las Vegas', 'Nevada', 'NV'),
  ('Reno', 'Nevada', 'NV'),
  ('Sparks', 'Nevada', 'NV'),
  ('Albany', 'New York', 'NY'),
  ('Binghamton', 'New York', 'NY'),
  ('Buffalo', 'New York', 'NY'),
  ('Freeport', 'New York', 'NY'),
  ('Hempstead', 'New York', 'NY'),
  ('Mount Vernon', 'New York', 'NY'),
  ('New Rochelle', 'New York', 'NY'),
  ('New York', 'New York', 'NY'),
  ('Niagara Falls', 'New York', 'NY'),
  ('Rochester', 'New York', 'NY'),
  ('Schenectady', 'New York', 'NY'),
  ('Syracuse', 'New York', 'NY'),
  ('Troy', 'New York', 'NY'),
  ('Utica', 'New York', 'NY'),
  ('Valley Stream', 'New York', 'NY'),
  ('White Plains', 'New York', 'NY'),
  ('Yonkers', 'New York', 'NY'),
  ('Akron', 'Ohio', 'OH'),
  ('Beavercreek', 'Ohio', 'OH'),
  ('Canton', 'Ohio', 'OH'),
  ('Cincinnati', 'Ohio', 'OH'),
  ('Cleveland', 'Ohio', 'OH'),
  ('Cleveland Heights', 'Ohio', 'OH'),
  ('Columbus', 'Ohio', 'OH'),
  ('Cuyahoga Falls', 'Ohio', 'OH'),
  ('Dayton', 'Ohio', 'OH'),
  ('Dublin', 'Ohio', 'OH'),
  ('Elyria', 'Ohio', 'OH'),
  ('Euclid', 'Ohio', 'OH'),
  ('Fairfield', 'Ohio', 'OH'),
  ('Findlay', 'Ohio', 'OH'),
  ('Grove City', 'Ohio', 'OH'),
  ('Hamilton', 'Ohio', 'OH'),
  ('Huber Heights', 'Ohio', 'OH'),
  ('Kettering', 'Ohio', 'OH'),
  ('Lakewood', 'Ohio', 'OH'),
  ('Lancaster', 'Ohio', 'OH'),
  ('Lima', 'Ohio', 'OH'),
  ('Lorain', 'Ohio', 'OH'),
  ('Mansfield', 'Ohio', 'OH'),
  ('Mentor', 'Ohio', 'OH'),
  ('Middletown', 'Ohio', 'OH'),
  ('Newark', 'Ohio', 'OH'),
  ('Parma', 'Ohio', 'OH'),
  ('Springfield', 'Ohio', 'OH'),
  ('Strongsville', 'Ohio', 'OH'),
  ('Toledo', 'Ohio', 'OH'),
  ('Warren', 'Ohio', 'OH'),
  ('Westerville', 'Ohio', 'OH'),
  ('Youngstown', 'Ohio', 'OH'),
  ('Broken Arrow', 'Oklahoma', 'OK'),
  ('Edmond', 'Oklahoma', 'OK'),
  ('Enid', 'Oklahoma', 'OK'),
  ('Lawton', 'Oklahoma', 'OK'),
  ('Midwest City', 'Oklahoma', 'OK'),
  ('Moore', 'Oklahoma', 'OK'),
  ('Muskogee', 'Oklahoma', 'OK'),
  ('Norman', 'Oklahoma', 'OK'),
  ('Oklahoma City', 'Oklahoma', 'OK'),
  ('Stillwater', 'Oklahoma', 'OK'),
  ('Tulsa', 'Oklahoma', 'OK'),
  ('Albany', 'Oregon', 'OR'),
  ('Beaverton', 'Oregon', 'OR'),
  ('Bend', 'Oregon', 'OR'),
  ('Corvallis', 'Oregon', 'OR'),
  ('Eugene', 'Oregon', 'OR'),
  ('Gresham', 'Oregon', 'OR'),
  ('Hillsboro', 'Oregon', 'OR'),
  ('Keizer', 'Oregon', 'OR'),
  ('Lake Oswego', 'Oregon', 'OR'),
  ('Medford', 'Oregon', 'OR'),
  ('Portland', 'Oregon', 'OR'),
  ('Salem', 'Oregon', 'OR'),
  ('Springfield', 'Oregon', 'OR'),
  ('Tigard', 'Oregon', 'OR'),
  ('Allentown', 'Pennsylvania', 'PA'),
  ('Altoona', 'Pennsylvania', 'PA'),
  ('Bethlehem', 'Pennsylvania', 'PA'),
  ('Erie', 'Pennsylvania', 'PA'),
  ('Harrisburg', 'Pennsylvania', 'PA'),
  ('Lancaster', 'Pennsylvania', 'PA'),
  ('Philadelphia', 'Pennsylvania', 'PA'),
  ('Pittsburgh', 'Pennsylvania', 'PA'),
  ('Reading', 'Pennsylvania', 'PA'),
  ('Scranton', 'Pennsylvania', 'PA'),
  ('State College', 'Pennsylvania', 'PA'),
  ('Wilkes-Barre', 'Pennsylvania', 'PA'),
  ('York', 'Pennsylvania', 'PA'),
  ('Cranston', 'Rhode Island', 'RI'),
  ('East Providence', 'Rhode Island', 'RI'),
  ('Pawtucket', 'Rhode Island', 'RI'),
  ('Providence', 'Rhode Island', 'RI'),
  ('Warwick', 'Rhode Island', 'RI'),
  ('Woonsocket', 'Rhode Island', 'RI'),
  ('Charleston', 'South Carolina', 'SC'),
  ('Columbia', 'South Carolina', 'SC'),
  ('Florence', 'South Carolina', 'SC'),
  ('Goose Creek', 'South Carolina', 'SC'),
  ('Greenville', 'South Carolina', 'SC'),
  ('Hilton Head Island', 'South Carolina', 'SC'),
  ('Mount Pleasant', 'South Carolina', 'SC'),
  ('North Charleston', 'South Carolina', 'SC'),
  ('Rock Hill', 'South Carolina', 'SC'),
  ('Spartanburg', 'South Carolina', 'SC'),
  ('Summerville', 'South Carolina', 'SC'),
  ('Sumter', 'South Carolina', 'SC'),
  ('Rapid City', 'South Dakota', 'SD'),
  ('Sioux Falls', 'South Dakota', 'SD'),
  ('Bartlett', 'Tennessee', 'TN'),
  ('Brentwood', 'Tennessee', 'TN'),
  ('Chattanooga', 'Tennessee', 'TN'),
  ('Clarksville', 'Tennessee', 'TN'),
  ('Cleveland', 'Tennessee', 'TN'),
  ('Collierville', 'Tennessee', 'TN'),
  ('Franklin', 'Tennessee', 'TN'),
  ('Germantown', 'Tennessee', 'TN'),
  ('Hendersonville', 'Tennessee', 'TN'),
  ('Jackson', 'Tennessee', 'TN'),
  ('Johnson City', 'Tennessee', 'TN'),
  ('Kingsport', 'Tennessee', 'TN'),
  ('Knoxville', 'Tennessee', 'TN'),
  ('Memphis', 'Tennessee', 'TN'),
  ('Murfreesboro', 'Tennessee', 'TN'),
  ('Nashville', 'Tennessee', 'TN'),
  ('Smyrna', 'Tennessee', 'TN'),
  ('Abilene', 'Texas', 'TX'),
  ('Allen', 'Texas', 'TX'),
  ('Amarillo', 'Texas', 'TX'),
  ('Arlington', 'Texas', 'TX'),
  ('Austin', 'Texas', 'TX'),
  ('Baytown', 'Texas', 'TX'),
  ('Beaumont', 'Texas', 'TX'),
  ('Bedford', 'Texas', 'TX'),
  ('Brownsville', 'Texas', 'TX'),
  ('Bryan', 'Texas', 'TX'),
  ('Burleson', 'Texas', 'TX'),
  ('Carrollton', 'Texas', 'TX'),
  ('Cedar Hill', 'Texas', 'TX'),
  ('Cedar Park', 'Texas', 'TX'),
  ('College Station', 'Texas', 'TX'),
  ('Conroe', 'Texas', 'TX'),
  ('Coppell', 'Texas', 'TX'),
  ('Corpus Christi', 'Texas', 'TX'),
  ('Dallas', 'Texas', 'TX'),
  ('Denton', 'Texas', 'TX'),
  ('DeSoto', 'Texas', 'TX'),
  ('Duncanville', 'Texas', 'TX'),
  ('Edinburg', 'Texas', 'TX'),
  ('El Paso', 'Texas', 'TX'),
  ('Euless', 'Texas', 'TX'),
  ('Flower Mound', 'Texas', 'TX'),
  ('Fort Worth', 'Texas', 'TX'),
  ('Friendswood', 'Texas', 'TX'),
  ('Frisco', 'Texas', 'TX'),
  ('Galveston', 'Texas', 'TX'),
  ('Garland', 'Texas', 'TX'),
  ('Georgetown', 'Texas', 'TX'),
  ('Grand Prairie', 'Texas', 'TX'),
  ('Grapevine', 'Texas', 'TX'),
  ('Haltom City', 'Texas', 'TX'),
  ('Harlingen', 'Texas', 'TX'),
  ('Houston', 'Texas', 'TX'),
  ('Huntsville', 'Texas', 'TX'),
  ('Hurst', 'Texas', 'TX'),
  ('Irving', 'Texas', 'TX'),
  ('Keller', 'Texas', 'TX'),
  ('Killeen', 'Texas', 'TX'),
  ('Lancaster', 'Texas', 'TX'),
  ('Laredo', 'Texas', 'TX'),
  ('League City', 'Texas', 'TX'),
  ('Lewisville', 'Texas', 'TX'),
  ('Longview', 'Texas', 'TX'),
  ('Lubbock', 'Texas', 'TX'),
  ('Mansfield', 'Texas', 'TX'),
  ('McAllen', 'Texas', 'TX'),
  ('McKinney', 'Texas', 'TX'),
  ('Mesquite', 'Texas', 'TX'),
  ('Midland', 'Texas', 'TX'),
  ('Mission', 'Texas', 'TX'),
  ('Missouri City', 'Texas', 'TX'),
  ('New Braunfels', 'Texas', 'TX'),
  ('North Richland Hills', 'Texas', 'TX'),
  ('Odessa', 'Texas', 'TX'),
  ('Pasadena', 'Texas', 'TX'),
  ('Pearland', 'Texas', 'TX'),
  ('Pflugerville', 'Texas', 'TX'),
  ('Pharr', 'Texas', 'TX'),
  ('Plano', 'Texas', 'TX'),
  ('Port Arthur', 'Texas', 'TX'),
  ('Richardson', 'Texas', 'TX'),
  ('Rockwall', 'Texas', 'TX'),
  ('Round Rock', 'Texas', 'TX'),
  ('Rowlett', 'Texas', 'TX'),
  ('San Angelo', 'Texas', 'TX'),
  ('San Antonio', 'Texas', 'TX'),
  ('San Marcos', 'Texas', 'TX'),
  ('Sherman', 'Texas', 'TX'),
  ('Sugar Land', 'Texas', 'TX'),
  ('Temple', 'Texas', 'TX'),
  ('Texarkana', 'Texas', 'TX'),
  ('Texas City', 'Texas', 'TX'),
  ('The Colony', 'Texas', 'TX'),
  ('Tyler', 'Texas', 'TX'),
  ('Victoria', 'Texas', 'TX'),
  ('Waco', 'Texas', 'TX'),
  ('Weslaco', 'Texas', 'TX'),
  ('Wichita Falls', 'Texas', 'TX'),
  ('Wylie', 'Texas', 'TX'),
  ('Bountiful', 'Utah', 'UT'),
  ('Draper', 'Utah', 'UT'),
  ('Layton', 'Utah', 'UT'),
  ('Lehi', 'Utah', 'UT'),
  ('Logan', 'Utah', 'UT'),
  ('Murray', 'Utah', 'UT'),
  ('Ogden', 'Utah', 'UT'),
  ('Orem', 'Utah', 'UT'),
  ('Provo', 'Utah', 'UT'),
  ('Riverton', 'Utah', 'UT'),
  ('Roy', 'Utah', 'UT'),
  ('Salt Lake City', 'Utah', 'UT'),
  ('Sandy', 'Utah', 'UT'),
  ('South Jordan', 'Utah', 'UT'),
  ('Spanish Fork', 'Utah', 'UT'),
  ('St. George', 'Utah', 'UT'),
  ('Taylorsville', 'Utah', 'UT'),
  ('West Jordan', 'Utah', 'UT'),
  ('West Valley City', 'Utah', 'UT'),
  ('Alexandria', 'Virginia', 'VA'),
  ('Blacksburg', 'Virginia', 'VA'),
  ('Charlottesville', 'Virginia', 'VA'),
  ('Chesapeake', 'Virginia', 'VA'),
  ('Danville', 'Virginia', 'VA'),
  ('Hampton', 'Virginia', 'VA'),
  ('Harrisonburg', 'Virginia', 'VA'),
  ('Leesburg', 'Virginia', 'VA'),
  ('Lynchburg', 'Virginia', 'VA'),
  ('Manassas', 'Virginia', 'VA'),
  ('Newport News', 'Virginia', 'VA'),
  ('Norfolk', 'Virginia', 'VA'),
  ('Portsmouth', 'Virginia', 'VA'),
  ('Richmond', 'Virginia', 'VA'),
  ('Roanoke', 'Virginia', 'VA'),
  ('Suffolk', 'Virginia', 'VA'),
  ('Virginia Beach', 'Virginia', 'VA'),
  ('Burlington', 'Vermont', 'VT'),
  ('Auburn', 'Washington', 'WA'),
  ('Bellevue', 'Washington', 'WA'),
  ('Bellingham', 'Washington', 'WA'),
  ('Bremerton', 'Washington', 'WA'),
  ('Burien', 'Washington', 'WA'),
  ('Edmonds', 'Washington', 'WA'),
  ('Everett', 'Washington', 'WA'),
  ('Federal Way', 'Washington', 'WA'),
  ('Kennewick', 'Washington', 'WA'),
  ('Kent', 'Washington', 'WA'),
  ('Kirkland', 'Washington', 'WA'),
  ('Lacey', 'Washington', 'WA'),
  ('Lakewood', 'Washington', 'WA'),
  ('Marysville', 'Washington', 'WA'),
  ('Olympia', 'Washington', 'WA'),
  ('Pasco', 'Washington', 'WA'),
  ('Puyallup', 'Washington', 'WA'),
  ('Redmond', 'Washington', 'WA'),
  ('Renton', 'Washington', 'WA'),
  ('Richland', 'Washington', 'WA'),
  ('Sammamish', 'Washington', 'WA'),
  ('Seattle', 'Washington', 'WA'),
  ('Shoreline', 'Washington', 'WA'),
  ('Spokane', 'Washington', 'WA'),
  ('Spokane Valley', 'Washington', 'WA'),
  ('Tacoma', 'Washington', 'WA'),
  ('Vancouver', 'Washington', 'WA'),
  ('Yakima', 'Washington', 'WA'),
  ('Appleton', 'Wisconsin', 'WI'),
  ('Beloit', 'Wisconsin', 'WI'),
  ('Brookfield', 'Wisconsin', 'WI'),
  ('Eau Claire', 'Wisconsin', 'WI'),
  ('Fond du Lac', 'Wisconsin', 'WI'),
  ('Green Bay', 'Wisconsin', 'WI'),
  ('Greenfield', 'Wisconsin', 'WI'),
  ('Janesville', 'Wisconsin', 'WI'),
  ('Kenosha', 'Wisconsin', 'WI'),
  ('La Crosse', 'Wisconsin', 'WI'),
  ('Madison', 'Wisconsin', 'WI'),
  ('Milwaukee', 'Wisconsin', 'WI'),
  ('New Berlin', 'Wisconsin', 'WI'),
  ('Oshkosh', 'Wisconsin', 'WI'),
  ('Racine', 'Wisconsin', 'WI'),
  ('Sheboygan', 'Wisconsin', 'WI'),
  ('Waukesha', 'Wisconsin', 'WI'),
  ('Wausau', 'Wisconsin', 'WI'),
  ('Wauwatosa', 'Wisconsin', 'WI'),
  ('West Allis', 'Wisconsin', 'WI'),
  ('Charleston', 'West Virginia', 'WV'),
  ('Huntington', 'West Virginia', 'WV'),
  ('Casper', 'Wyoming', 'WY'),
  ('Cheyenne', 'Wyoming', 'WY')
ON CONFLICT (name, state_code) DO NOTHING;
-- Wipe app data so NOT NULL city_id can be applied (local/dev expectation per Step 30).
TRUNCATE TABLE
  comment_likes,
  comments,
  messages,
  conversation_participants,
  conversations,
  event_lineup,
  events,
  mixes,
  mix_likes,
  follows,
  profiles
CASCADE;

DROP INDEX IF EXISTS public.idx_profiles_location;
DROP INDEX IF EXISTS public.idx_events_location;

ALTER TABLE profiles
  ADD COLUMN city_id uuid NOT NULL DEFAULT '11111111-1111-4111-8111-111111111111'
  REFERENCES cities(id);

ALTER TABLE profiles
  DROP COLUMN city,
  DROP COLUMN state;

ALTER TABLE profiles
  ALTER COLUMN city_id DROP DEFAULT;

ALTER TABLE events
  ADD COLUMN city_id uuid NOT NULL DEFAULT '11111111-1111-4111-8111-111111111111'
  REFERENCES cities(id);

ALTER TABLE events
  DROP COLUMN city,
  DROP COLUMN state;

ALTER TABLE events
  ALTER COLUMN city_id DROP DEFAULT;

CREATE INDEX idx_profiles_city_id ON profiles(city_id);
CREATE INDEX idx_events_city_id ON events(city_id);
